# 예외 처리

자바에서는 에러 이외에 예외(exception)라고 부르는 오류가 있다. 예외는 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류를 말한다. 예외가 발생하면 프로그램은 종료되지만, 예외 처리(Exception Handling)를 통해 프로그램을 종료하지 않고 정상 실행 상태가 유지되도록 할 수 있다.

예외는 두 가지 종류가 있다.
1. 일반 예외(Exception)
컴파일러 체크 예외라고도 한다. 자바 소스를 컴파일하는 과정에서 예외 처리 코드가 필요한지 검사한다. 만약 예외 처리 코드가 없다면 컴파일 오류가 발생한다.

2. 실행 예외(Runtime Exception)
컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외. 컴파일 시 예외 처리를 확인하지 않을 뿐 예외 처리가 필요하다.

## 실행 예외
실행 예외는 자바 컴파일러가 체크를 하지 않기 때문에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다. 만약 실행 예외에 처리 코드를 삽입하지 않으면 프로그램은 종료된다. 

이어질 내용은 자바 프로그램에서 자주 발생되는 실행 예외이다.

### NullPointerException
java.lang.NullPointerException은 자바에서 가장 자주 발생되는 실행 예외이다. **객체 참조가 없는 상태, null 값을 참조 변수로 객체 접근 연산자인 도트( . )를 사용했을 때 발생한다.** 객체가 없는 상태에서 객체를 사용하려 했으니 예외가 발생하는 것.

<pre>
<code>
public class Main {
    public static void main(String[] args) {
        String data = null;
        System.out.println(data.toString()); // data 변수는 null 값을 가지고 있기 때문에 String 객체를 참조하고 있지 않다. 
    }
}
</code>
</pre>

### ArrayIndexOutOfoundsException
**배열에서 인덱스 범위를 초과하여 사용할 경우** java.lang.ArrayIndexOutOfoundsException이 발생한다. 

<pre>
<code>
public class Main {
    public static void main(String[] args) {
        int[] arr = {1,2,3};

        System.out.println(arr[3]); // 배열 arr의 값은 arr[0] ~ arr[2]까지 참조 가능하다.
    }
}
</code>
</pre>

### NumberFormatException
특정 데이터 타입을 숫자로 변환할 때 숫자롸 변환될 수 없는 문자가 포함되어 있다면 java.lang.NumberFormatException을 발생시킨다.

<pre>
<code>
public class Main {
    public static void main(String[] args) {
        
        String data1 = "777";
        String data2 = "a777";

        int value1 = Integer.parseInt(data1);
        int value2 = Integer.parseInt(data2); // NumberFormatException 발생

    }
}
</code>
</pre>

### ClassCastException
타입 변환(Casting)은 상위 클래스와 하위 클래스 간에 발생하고 구현 클래스와 인터페이스 간에도 발생한다. 이러한 관계가 아니라면 클래스는 다른 클래스로 타입 변환할 수 없다. 억지로 타입 변환을 시도할 경우 ClassCastException이 발생한다. 

이 에러를 방지하려면 타입 변환 전에 타입 변환이 가능한지 instanceof 연산자로 확인하는 것이 좋다. 결과가 true이면 좌항 객체를 우항 타입으로 변환이 가능하다는 뜻이다.

## 예외 처리 코드
예외가 발생했을 경우 프로그램의 갑작스로운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 코드를 예외 처리 코드라고 한다. 
자바 컴파일러는 일반 예외가 발생할 가능성이 있는 코드의 경우 컴파일 오류를 통해 개발자에게 강제적으로 예외 처리를 요구하지만 실행 예외는 컴파일러가 체크해주지 않기 때문에 개발자가 알아서 처리해야 한다. 

예외 처리 코드는 try-catch-finally 블록을 이용한다. 이 블록은 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해준다. 

<pre>
<code>
try {

    예외 발생 가능 코드

} catch(예외클래스 e) {
    
    예외 처리

} finally {
    
    항상 실행;

}
</code>
</pre>
try 블록의 코드가 정상 실행되면 catch 블록을 건너뛰고 finally 블록의 코드를 실행한다.
try 블록의 코드에서 예외가 발생하면 catch 블록의 코드를 실행한다. 
finally 블록은 생략 가능하다. 예외 발생 여부와 상관없이 항상 실행할 내용이 있다면 finally 블록을 작성하면 된다.

<pre>
<code>
public class Main {
    public static void main(String[] args) {
        try {
            Class clazz = Class.forName("jaa.lang.String2");
        } catch(ClassNotFoundException e) {
            System.out.println("클래스가 존재하지 않음.");
        }
    }
}
</code>
</pre>
Class.forName() 메소드는 매개값으로 주어진 클래스가 존재하면 Class 객체를 리턴하지만, 존재하지 않으면 ClassNotFoundException 예외를 발생시킨다.
ClassNotFoundException 예외는 일반 예외이므로 컴파일러는 개발자에게 예외 처리 코드를 작성하도록 요구한다.

ArrayIndexOutOfBoundsException이나 NumberFormatException과 같은 실행 예외는 컴파일러가 예외 처리 코드를 체크하지 않기 때문에 컴파일러가 알려주지 않는다. 따라서 개발자의 재량껏 예외 처리를 해야한다.

<pre>
<code>
public class Main {
    public static void main(String[] args) {
        String data1 = null;
        String data2 = null;

        try{
            data1 = args[0];
            data2 = args[1];
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println("실행 매개값이 부족.");
            return;
        }

        try{
            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2);
            int result = value1 + value2;
            System.out.println(result);
        }catch(NumberFormatException e){
            System.out.println("숫자로 변환할 수 없음.");
        }finally{
            System.out.println("다시 실행하시오.");
        }
    }
}
</code>
</pre>

## 예외 종류에 따른 처리 코드

### 다중 catch
try 블록 내부는 다양한 종류의 예외가 발생할 수 있기 때뭉네 발생되는 예외별로 예외 처리를 다르게 하려면 다중 catch 블록이 필요하다.
try 블록에서 예외가 동시에 발생하지 않기 때문에 catch 블록은 하나만 실행된다.

<pre>
<code>
public class Main {
    public static void main(String[] args) {
       
        try{
            String data1 = args[0];
            String data2 = args[1];
            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2);
            int result = value1 + value2;
            System.out.println(result);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println("실행 매개값이 부족.");
        }catch(NumberFormatException e){
            System.out.println("숫자로 변환할 수 없음.");
        }finally{
            System.out.println("다시 실행하시오.");
        }
    }
}
</code>
</pre>

### catch 순서
다중 catch문을 작성할 때 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다. try-catch-finally 블록은 위에서 아래로 실행되는데, 만약 상위 예외 클래스의 catch 블록이 위에 있다면 하위 예외 클래스의 catch 블록은 실행되지 않는다. 왜냐하면 하위 예외는 상위 예외를 상속했기 때문에 상위 예외 타입도 되기 때문이다.

다음은 잘못된 코딩의 예시이다.
<pre>
<code>
try{

    ArrayIndexOutOfBoundsException 발생

    NumberFormatException 발생

}catch(Exception e){
    예외처리1
}catch(ArrayIndexOutOfBoundsException e){
    예외처리2
}
</code>
</pre>
ArrayIndexOutOfBoundsException, NumberFormatException모두 Exception을 상속받기 때문에 첫 번째 catch 블록만 선택되어 실행된다. 두 번째 catch 블록은 실행되지 않는다. 위 코드는 다음과 같이 수정해야 한다.
<pre>
<code>
try{

    ArrayIndexOutOfBoundsException 발생

    Exception 발생

}catch(ArrayIndexOutOfBoundsException e){
    예외처리1
}catch(Exception e){
    예외처리2
}
</code>
</pre>

### 멀티 catch
자바7부터 하나의 catch 블록에 여러 개의 예외를 처리할 수 있도록 멀티 catch 기능을 추가했다. catch 괄호 안에 동일하게 처리하고 싶은 예외를 | 로 연결하면 된다.

<pre>
<code>
try{

    ArrayIndexOutOfBoundsException 또는 NumberFormatException 발생

    Exception을 발생

}catch(ArrayIndexOutOfBoundsException | NumberFormatException e){
    예외처리1
}catch(Exception e){
    예외처리2
}
</code>
</pre>

## 자동 리소스 닫기
자바7에서 새로 추가된 try-with-resources를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체(각종 입출력 스트림, 서버 소켓, 소켓, 각종 채널)의 close() 메소드를 호출해서 안전하게 리소스를 닫는다. 

<pre>
<code>
try(FileInputStream fis = new FileInputStream("file.txt")){

}catch(IOException e){

}
</code>
</pre>
try 블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하게 되면 자동으로 FileInputStream의 close() 메소드가 호출된다. try에서 예외가 발생하면 우선 close()로 리소스를 닫고 catch블록을 실행한다. 

try-with-resources를 사용하려면 리소스 객체는 java.lang.AutoCloseable 인터페이스를 구현하고 있어야 한다. AutoCloseable에는 close() 메소드가 정의되어 있는데 try-with-resources 인터페이스를 찾아 "All Known Implementing Classes:"를 보면 try-with-resources와 함께 사용할 수 있는 리소스가 어떤 것이 있는지 알 수 있다.

## 사용자 정의 예외와 예외 발생
자바 표준 API에서 제공하는 예외 클래스로 부족한 경우 사용자 정의 예외 클래스를 선언하여 사용한다.

### 사용자 정의 예외 클래스 선언
사용자 정의 예외 클래스는 컴파일러가 체크하는 일반 예외로 선언할 수도, 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다. 
일반 예외로 선언하는 경우 Exception을 상속하고, 실행 예외로 선언할 경우 RuntimeException을 상속하면 된다.

<pre>
<code>
public class XXXException extends [ Exception | RuntimeException ] {
    public XXXException() {}
    public XXXException(String message) { super(message) }
}
</code>
</pre>

사용자 정의 예외 클래스도 필드, 생성자, 메소드 선언들을 포함할 수 있지만 대부분 생성자 선언만을 포함한다. 생성자는 두 개를 선언하는 것이 일반적인데, 하나는 매개 변수가 없는 기본 생성자, 다른 하나는 예외 발생 원인(예외 메시지)을 전달하기 위해 String 타입의 매개 변수를 갖는 생성자이다. String 타입의 매개변수를 갖는 생성자는 상위 클래스의 생성자를 호출하여 예외 메시지를 넘겨준다. 예외 메시지의 용도는 catch{} 블록의 예외 처리 코드에서 이용하기 위함이다.

다음은 잔고 부족 사용자 정의 예외 클래스 예시이다.
<pre>
<code>
public class BalanceInsufficientException extends Exception {
    public BalanceInsufficientException() {}
    public BalanceInsufficientException(String message) { 
        super(message) 
        }
}
</code>
</pre>
BalanceInsufficientException은 Exception을 상속하기 때문에 컴파일러에 의해 체크되는 예외가 된다. 따라서 소스 작성 시 try-catch 블록으로 예외 처리가 필요하다.

### 예외 발생시키기
코드에서 예외를 발생시키는 방법은 다음과 같다.
<pre>
<code>
throw new XXXException();
throw new XXXException("메시지");
</code>
</pre>
예외 객체 생성 시 기본 생성자 또는 예외 메시지를 갖는 생성자 중 어떤 것을 사용해도 괜찮다. 만약 catch 블록에서 예외 메시지가 필요하다면 예외 메시지를 갖는 생성자를 이용해야 한다. 예외 발생 코드를 가지고 있는 메소드는 내부에서 try-catch 블록으로 예외 처리가 가능하지만, 대부분은 자신을 호출한 곳에서 예외를 처리하도록 throws 키워드로 예외를 떠넘긴다.

<pre>
<code>
public void method() throws XXXException {
    throw new XXXException("메시지");
}
</code>
</pre>
그렇기 때문에 throws 키워드를 포함하고 있는 메소드는 호출한 곳에서 다음과 같이 에외 처리를 해주어야 한다.
<pre>
<code>
try{
    method();
}catch(XXXException e){
    // 예외 처리
}
</code>
</pre>

다음은 은행 계좌(Account) 클래스를 작성한 것이다. 출금(withdraw) 메소드에서 잔고(balance) 필드와 출금액을 비교하여 잔고가 부족하면 BalanceInsufficientException을 발생시킨다.
<pre>
<code>
public class Account {
    private long balance;

    public Account(){}

    public long getBalance(){
        return balance;
    }
    public void deposit(int money){
        balance += money;
    }
    public void withdraw(int money) throws BalanceInsufficientException {
        if(balance < money){
            throw new BalanceInsufficientException("잔고 부족" + (money - balance) + "모자람");
        }
        balance -= money;
    }
}
</code>
</pre>

## 예외 정보 얻기
try 블록에서 예외가 발생되면 예외 객체는 catch 블록의 매개 변수에서 참조하게 되므로 매개 변수를 이용하면 예외 객체의 정보를 얻을 수 있다. 모든 예외 객체는 Exception을 상속하기 때문에 Exception이 가지고 있는 메소드들을 모든 예외 객체에서 호출할 수 있다. 그 중 가장 많이 사용되는 메소드는 getMessage()와 printStackTrace()이다. 예외를 발생시킬 때 다음과 같이 String 타입의 메시지를 갖는 생성자를 이용했다면, 메시지는 자동적으로 예외 객체 내부에 저장된다.
<pre>
<code>
throw new XXXException("예외 메시지");
</code>
</pre>

예외 메시지의 내용에는 왜 예외가 발생했는지에 대한 간단한 설명이 포함된다. 좀 더 상세한 원인을 세분화하기 위해 예외 코드를 포함하기도 하는데, 예를 들어 데이터베이스에서 발생한 오류들은 예외 코드가 예외 메시지로 전달된다. 이와 같은 예외 메시지는 다음과 같이 catch 블록에서 getMessage() 메소드의 리턴값으로 얻을 수 있다.
<pre>
<code>
}catch(Exception e){
    String message = e.getMessage();
}
</code>
</pre>

printStackTrace()는 메소드 이름에서도 알 수 있듯이 예외 발생 코드를 추적해서 모두 콘솔에 출력한다. 어떤 예외가 어디에서 발생했는지 상세하게 출력해주기 때문에 프로그램을 테스트하면서 오류를 찾을 때 활용된다.
<pre>
<code>
try{

}catch(예외클래스 e){

    // 예외가 가지고 있는 Message 얻기
    String message = e.getMessage();

    // 예외의 발생 경로를 추적
    e.printStackTrace();
}
</code>
</pre>

다음 AccountExample 클래스는 Account 클래스를 이용해서 예금과 출금을 한다. 출금할 때 withdraw() 메소드를 사용하므로 예외 처리가 꼭 필요하다. 예외 처리 코드에서 BalanceInsufficientException 객체의 getMessage() 메소드와 printStackTracee() 메소드로 예외에 대한 정보를 얻어보자.
<pre>
<code>
public class AccountExample {
    public static void main(String[] args) {
        Account account = new Account();

        // 예금하기
        account.deposit(77777);
        System.out.println("예금액: " + account.getBalance());

        // 출금하기
        try{
            account.withdraw(1000000);
        }catch(BalanceInsufficientException e){
            String message = e.getMessage();
            System.out.println(message);
            System.out.println("===============");
            e.printStackTrace();
        }
    }
}
</code>
</pre>

# 출처
* [이것이 자바다](http://www.kyobobook.co.kr/product/detailViewKor.laf?ejkGb=KOR&mallGb=KOR&barcode=9788968481475&orderClick=LAG&Kc=)